import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Traversy Courses',
  description: 'Generated by Truong Anh Vu',
  keywords: 'nextjs, reactjs, tailwind css',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <main className=''>
          {children}
        </main>
      </body>
    </html>
  )
}
